Path:
  scene: "LH-VLN/data/hm3d/"
  scene_dataset: "LH-VLN/data/hm3d/hm3d_annotated_basis.scene_dataset_config.json"
  
  episode_data: "LH-VLN/data/episode_task"
  task_data: "LH-VLN/data/task"
  step_task_data: "LH-VLN/data/step_task"
  train_batch: ['/batch_1', '/batch_2', '/batch_3', '/batch_4', '/batch_5']
  val_batch: ['/batch_6']
  test_batch: ['/batch_7', '/batch_8']
  split_by_scene: True

  save_checkpoints: "LH-VLN/save_checkpoints"

  tensorboard_path: "LH-VLN/run"
  output_dir: "LH-VLN/output"

Train:
  mode: 'test'
  tensorboard: False
  best_checkpoint: null
  load_checkpoint: False
  save_ckpt_per_epochs: 10

  batch_size: 1
  num_epochs: 20
  ignoreid: -100
  max_step: 500
  gradient_accumulation_step: 2
  num_warmup_steps: 1000

  success_dis: 1

Model:
  model_name: "Random"
